### ISSUE TITLE
util-linux Ubuntu PPA breaks exFAT automount

### ISSUE THREAD

**Issue by mardy** [xeron/ubuntu-packages#3]
Hi Ivan, I spent some time today trying to understand why my exFAT-formatted SD card was not automounted. I had the util-linux installed from your PPA (on Trusty), and just now I found out that the reason of the problem is that the blkid provided by your util-linux does not recognize exFAT partitions:
```
    $ blkid /dev/sdc1
    $
```
But, if I disable your PPA and use the libblkid1 package which comes with Trusty, it works:
```
    $ blkid /dev/sdc1
    /dev/sdc1: TYPE="exfat"
    $
```

**Comment by xeron** [comment]
Hi there.

Thank you for your report. I don't really support this version since we already have new `util-linux` in newer ubuntu releases.

I'll try to find some time to update it, but I won't promise that.

**Comment by xeron** [comment]
I've updated package to the version from http://packages.ubuntu.com/vivid-updates/util-linux

You could try to update and check if it fixes your issue.
