### ISSUE TITLE
Sonata on Xenial requires non-existent package

### ISSUE THREAD

**Issue by CaviaPorcellus** [xeron/ubuntu-packages#4]
The sonata package you provided for in your PPA (thanks for doing that!) has a problem in Ubuntu 16.04. The older Wily packages work (i.e. the updated Sonata runs just fine), but apt now coughs up errors, saying that the sonata package requires "python3-gobject" which doesn't exist in the repos.

Thanks.

**Comment by xeron** [comment]
Hi! Thank you for reporting. Looks like we need to change this dependency to `python3-gi` package. I'll take a look.

**Comment by xeron** [comment]
Should be fixed now. I'm also updating and building `python-mpd2` for Xenial.

**Comment by aibaraiduas** [comment]
Thanks, works great now.
